# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# patreon: evillt
open_collective: # Replace with a single Open Collective username
ko_fi: evillt
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://2nthony.notion.site/Buy-2nthony-Coffee-d67a508cd58e4896bfb50c7112f93f51
